apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - description: ssh url for git-repo
      name: source-repo
      type: string
    - description: ssh url for gitops-repo
      name: gitops-repo
      type: string
    - description: Docker image repository
      name: docker-image
      type: string
    - description: Application name
      name: app-name
      type: string
    - default: ./Dockerfile
      description: sets the Dockerfile to build
      name: dockerfile
      type: string
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: $(params.source-repo)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: build-and-push-image
      params:
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: TLSVERIFY
          value: 'false'
        - name: IMAGE
          value: $(params.docker-image)
      runAfter:
        - clone-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline-shared-data
    - name: kustomize-build
      params:
        - name: app-name
          value: $(params.app-name)
        - name: app-namespace
          value: $(context.pipelineRun.namespace)
        - name: image-with-tag
          value: $(params.docker-image)
      runAfter:
        - build-and-push-image
      taskRef:
        kind: Task
        name: kustomize-build
      workspaces:
        - name: source
          workspace: pipeline-shared-data
    - name: gitops
      params:
        - name: directory
          value: '$(params.app-name)'
        - name: gitops-repo
          value: '$(params.gitops-repo)'
      runAfter:
        - kustomize-build
      taskRef:
        kind: Task
        name: gitops
      workspaces:
        - name: source
          workspace: pipeline-shared-data
  workspaces:
    - name: pipeline-shared-data
