apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- route.yaml

images:
- name: image-registry.openshift-image-registry.svc:5000/tekton-demo/cloud-native-sample-app
  newTag: v1.0.0
