kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: cloudnative
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: cloudnative
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
